#!/usr/bin/env python3
"""Visualize pkl files generated by ``new_tool/unified_processor_raw.py``.

This script is independent from nuScenes dataset classes.  It only depends on
fields emitted by the N7 OD converter:

    {
        "infos": [
            {
                "token": "...",
                "timestamp": 171...,
                "cams": {
                    "cam0": {
                        "data_path": "relative/or/absolute/image.jpg",
                        "cam_intrinsic": [[...], [...], [...]],
                        "sensor2lidar_rotation": [[...], [...], [...]],
                        "sensor2lidar_translation": [x, y, z],
                        "distortion": [...]
                    },
                    ...
                },
                "gt_boxes": [[x, y, z, l, w, h, yaw], ...],
                "gt_names": ["car", ...],
                "gt_velocity": [[vx, vy], ...]
            },
            ...
        ],
        "metadata": {...}
    }

Coordinate convention expected by this visualizer:

    x: vehicle front
    y: vehicle left
    z: up
    origin: N7 top lidar, unless converter metadata says otherwise

The projection code mirrors ``CustomMultiViewDataset._lidar2img_from_cam_info``.
This is deliberate: if a projected GT box is wrong here, the training-time
Fast-BEV projection is likely wrong for the same pkl.

Typical usage:

    python new_tool/unified_processor_raw.py \
        --data-path /data/N7 \
        --datasets 2025_04_18_2k \
        --sets train val \
        --info-json data/info_json/2025_04_18_2k_byd_info.json \
        --output-dir /data/N7/fastbev_pkl \
        --extra-tag custom_fastbev

    python new_tool/draw_gt_pkl.py \
        --pkl /data/N7/fastbev_pkl/custom_fastbev_infos_train.pkl \
        --data-root /data/N7 \
        --output-dir /data/N7/fastbev_vis/train \
        --max-frames 200

If image paths in the pkl are relative, ``--data-root`` must be the same root
passed to converter ``--data-path``.
"""

from __future__ import annotations

import argparse
import logging
import math
import pickle
import re
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

import cv2
import numpy as np
from tqdm import tqdm


logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)
cv2.setNumThreads(4)

# Human inspection order for the converter default cameras:
#   front row: left_front, front_wide, right_front
#   rear row:  left_back, back,       right_back
DEFAULT_MOSAIC_ORDER = ['cam9', 'cam0', 'cam11', 'cam8', 'cam3', 'cam10']

# OpenCV uses BGR, not RGB.
DEFAULT_COLORS = [
    (0, 255, 0), (0, 128, 255), (255, 0, 0), (255, 255, 0),
    (0, 255, 255), (255, 0, 255), (180, 80, 0), (80, 180, 0),
    (180, 0, 180), (255, 255, 255),
]

# Corner layout returned by corners_from_boxes:
#   bottom: 0--1      top: 4--5
#           |  |           |  |
#           3--2           7--6
BOX_EDGES = [
    (0, 1), (1, 2), (2, 3), (3, 0),
    (4, 5), (5, 6), (6, 7), (7, 4),
    (0, 4), (1, 5), (2, 6), (3, 7),
]
FRONT_EDGES = {(0, 1), (4, 5)}
UNDISTORT_CACHE: Dict[Tuple, Tuple[np.ndarray, np.ndarray, np.ndarray]] = {}


def load_fastbev_pkl(path: Path) -> Tuple[List[Dict], Dict]:
    """Load either converter dict pkl or a legacy bare-list pkl."""
    with path.open('rb') as f:
        payload = pickle.load(f)

    if isinstance(payload, dict):
        infos = payload.get('infos', [])
        metadata = payload.get('metadata', {})
    elif isinstance(payload, list):
        infos = payload
        metadata = {}
    else:
        raise TypeError(f'Unsupported pkl payload type: {type(payload)!r}')

    if not isinstance(infos, list):
        raise TypeError(f'Expected infos to be list, got {type(infos)!r}')
    return infos, metadata


def sanitize_filename(text: str, max_len: int = 180) -> str:
    text = re.sub(r'[^0-9A-Za-z_.-]+', '_', str(text))
    return text[:max_len]


def resolve_image_path(data_root: Path, data_path: str) -> Path:
    """Resolve camera image path from pkl.

    The converter stores image paths relative to ``--data-path`` when possible,
    so this script resolves relative paths under ``--data-root``.
    """
    path = Path(data_path)
    if path.is_absolute():
        return path
    return data_root / path


def to_numpy(value, dtype=np.float32) -> np.ndarray:
    return np.asarray(value, dtype=dtype)


def get_class_names(metadata: Dict, infos: Sequence[Dict]) -> List[str]:
    if metadata.get('classes'):
        return list(metadata['classes'])
    names: List[str] = []
    for info in infos:
        for name in info.get('gt_names', []):
            name = str(name)
            if name not in names:
                names.append(name)
    return names or ['unknown']


def class_color(name: str, class_names: Sequence[str]) -> Tuple[int, int, int]:
    try:
        idx = class_names.index(name)
    except ValueError:
        idx = len(class_names)
    return DEFAULT_COLORS[idx % len(DEFAULT_COLORS)]


def choose_camera_order(info: Dict, requested: Optional[Sequence[str]]) -> List[str]:
    cams = info.get('cams', {})
    if requested:
        missing = [cam for cam in requested if cam not in cams]
        if missing:
            logger.warning('Requested cameras missing in token=%s: %s', info.get('token'), missing)
        return [cam for cam in requested if cam in cams]
    ordered = [cam for cam in DEFAULT_MOSAIC_ORDER if cam in cams]
    ordered.extend([cam for cam in cams.keys() if cam not in ordered])
    return ordered


def compute_lidar2img(cam_info: Dict, intrinsic_override: Optional[np.ndarray] = None) -> np.ndarray:
    """Build the 4x4 lidar-to-image matrix used by Fast-BEV.

    ``sensor2lidar_rotation`` and ``sensor2lidar_translation`` are camera-to-lidar
    extrinsics in the converter pkl.  Fast-BEV's dataset uses the OpenMMLab
    row-vector convention below, so the same formula is used here:

        lidar2cam_r = inv(sensor2lidar_r)
        lidar2cam_t = sensor2lidar_t @ lidar2cam_r.T
        lidar2img   = K4x4 @ lidar2cam_rt.T

    Keeping this exactly aligned with ``CustomMultiViewDataset`` makes the
    visualization a training-input sanity check rather than an independent
    drawing guess.
    """
    intrinsic = to_numpy(intrinsic_override if intrinsic_override is not None else cam_info['cam_intrinsic'])
    sensor2lidar_r = to_numpy(cam_info['sensor2lidar_rotation'])
    sensor2lidar_t = to_numpy(cam_info['sensor2lidar_translation']).reshape(3)

    lidar2cam_r = np.linalg.inv(sensor2lidar_r)
    lidar2cam_t = sensor2lidar_t @ lidar2cam_r.T

    lidar2cam_rt = np.eye(4, dtype=np.float32)
    lidar2cam_rt[:3, :3] = lidar2cam_r.T
    lidar2cam_rt[3, :3] = -lidar2cam_t

    viewpad = np.eye(4, dtype=np.float32)
    viewpad[:intrinsic.shape[0], :intrinsic.shape[1]] = intrinsic
    return (viewpad @ lidar2cam_rt.T).astype(np.float32)


def undistort_if_requested(
    image: np.ndarray,
    cam_info: Dict,
    enabled: bool,
    alpha: float,
) -> Tuple[np.ndarray, np.ndarray]:
    """Optionally undistort image and return the intrinsic used for projection.

    Default is no undistortion because raw image + raw K is the safest check.
    If ``--undistort`` is enabled, OpenCV returns ``new_K`` and projection uses
    that adjusted intrinsic to keep boxes aligned on the rectified image.
    """
    intrinsic = to_numpy(cam_info['cam_intrinsic'])
    if not enabled:
        return image, intrinsic

    distortion = np.asarray(cam_info.get('distortion', []), dtype=np.float64).reshape(-1)
    if distortion.size == 0 or np.allclose(distortion, 0):
        return image, intrinsic

    h, w = image.shape[:2]
    dist_full = np.zeros(8, dtype=np.float64)
    dist_full[:min(distortion.size, dist_full.size)] = distortion[:dist_full.size]
    cache_key = (h, w, tuple(intrinsic.reshape(-1)), tuple(dist_full), float(alpha))

    if cache_key not in UNDISTORT_CACHE:
        new_k, _ = cv2.getOptimalNewCameraMatrix(intrinsic, dist_full, (w, h), alpha, (w, h))
        map1, map2 = cv2.initUndistortRectifyMap(intrinsic, dist_full, None, new_k, (w, h), cv2.CV_16SC2)
        UNDISTORT_CACHE[cache_key] = (map1, map2, new_k.astype(np.float32))

    map1, map2, new_k = UNDISTORT_CACHE[cache_key]
    return cv2.remap(image, map1, map2, interpolation=cv2.INTER_LINEAR), new_k


def corners_from_boxes(boxes: np.ndarray) -> np.ndarray:
    """Convert ``[x, y, z, l, w, h, yaw]`` boxes to 8 lidar-frame corners."""
    if boxes.size == 0:
        return np.zeros((0, 8, 3), dtype=np.float32)

    boxes = boxes[:, :7].astype(np.float32)
    corners = np.zeros((boxes.shape[0], 8, 3), dtype=np.float32)
    for i, box in enumerate(boxes):
        x, y, z, length, width, height, yaw = [float(v) for v in box]
        if length <= 0 or width <= 0 or height <= 0:
            continue
        local = np.array([
            [ length / 2,  width / 2, -height / 2],
            [ length / 2, -width / 2, -height / 2],
            [-length / 2, -width / 2, -height / 2],
            [-length / 2,  width / 2, -height / 2],
            [ length / 2,  width / 2,  height / 2],
            [ length / 2, -width / 2,  height / 2],
            [-length / 2, -width / 2,  height / 2],
            [-length / 2,  width / 2,  height / 2],
        ], dtype=np.float32)
        c, s = math.cos(yaw), math.sin(yaw)
        rot = np.array([[c, -s], [s, c]], dtype=np.float32)
        local[:, :2] = local[:, :2] @ rot.T
        local += np.array([x, y, z], dtype=np.float32)
        corners[i] = local
    return corners


def project_corners(corners: np.ndarray, lidar2img: np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
    corners_h = np.concatenate([corners, np.ones((corners.shape[0], 1), dtype=np.float32)], axis=1)
    proj = (lidar2img @ corners_h.T).T
    depth = proj[:, 2]
    uv = proj[:, :2] / np.maximum(depth[:, None], 1e-6)
    return uv, depth


def draw_projected_box(
    image: np.ndarray,
    corners: np.ndarray,
    lidar2img: np.ndarray,
    label: str,
    color: Tuple[int, int, int],
    min_depth: float,
) -> None:
    uv, depth = project_corners(corners, lidar2img)
    for start, end in BOX_EDGES:
        if depth[start] <= min_depth or depth[end] <= min_depth:
            continue
        pt1 = tuple(np.round(uv[start]).astype(int).tolist())
        pt2 = tuple(np.round(uv[end]).astype(int).tolist())
        thickness = 3 if (start, end) in FRONT_EDGES else 2
        cv2.line(image, pt1, pt2, color, thickness, lineType=cv2.LINE_AA)

    valid = depth > min_depth
    if not np.any(valid):
        return
    h, w = image.shape[:2]
    valid_uv = uv[valid]
    inside = ((valid_uv[:, 0] >= 0) & (valid_uv[:, 0] < w) &
              (valid_uv[:, 1] >= 0) & (valid_uv[:, 1] < h))
    if not np.any(inside):
        return
    anchor = valid_uv[inside][np.argmin(valid_uv[inside][:, 1])]
    x, y = np.round(anchor).astype(int).tolist()
    cv2.putText(image, label, (x, max(18, y - 4)), cv2.FONT_HERSHEY_SIMPLEX, 0.6, color, 2, cv2.LINE_AA)


def draw_boxes_on_camera(
    image: np.ndarray,
    boxes: np.ndarray,
    names: Sequence[str],
    cam_info: Dict,
    class_names: Sequence[str],
    undistort: bool,
    undistort_alpha: float,
    min_depth: float,
) -> np.ndarray:
    image, intrinsic = undistort_if_requested(image, cam_info, undistort, undistort_alpha)
    lidar2img = compute_lidar2img(cam_info, intrinsic_override=intrinsic)
    for corners, name in zip(corners_from_boxes(boxes), names):
        draw_projected_box(image, corners, lidar2img, str(name), class_color(str(name), class_names), min_depth)
    return image


def resize_to_width(image: np.ndarray, width: int) -> np.ndarray:
    if width <= 0:
        return image
    h, w = image.shape[:2]
    if w == width:
        return image
    scale = width / float(w)
    return cv2.resize(image, (width, max(1, int(round(h * scale)))), interpolation=cv2.INTER_AREA)


def pad_to_shape(image: np.ndarray, height: int, width: int) -> np.ndarray:
    canvas = np.zeros((height, width, 3), dtype=np.uint8)
    h, w = image.shape[:2]
    canvas[:h, :w] = image
    return canvas


def placeholder_image(width: int, height: int, text: str) -> np.ndarray:
    image = np.zeros((height, width, 3), dtype=np.uint8)
    cv2.putText(image, text, (20, height // 2), cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0, 0, 255), 2, cv2.LINE_AA)
    return image


def render_camera_panel(
    info: Dict,
    cam_id: str,
    data_root: Path,
    boxes: np.ndarray,
    names: Sequence[str],
    class_names: Sequence[str],
    camera_width: int,
    undistort: bool,
    undistort_alpha: float,
    min_depth: float,
) -> np.ndarray:
    cam_info = info['cams'][cam_id]
    image_path = resolve_image_path(data_root, cam_info['data_path'])
    image = cv2.imread(str(image_path), cv2.IMREAD_COLOR)
    if image is None:
        logger.warning('Cannot read image: %s', image_path)
        image = placeholder_image(camera_width, int(camera_width * 9 / 16), f'missing {cam_id}')
    else:
        image = draw_boxes_on_camera(image, boxes, names, cam_info, class_names, undistort, undistort_alpha, min_depth)
    image = resize_to_width(image, camera_width)
    cv2.rectangle(image, (0, 0), (220, 34), (0, 0, 0), -1)
    cv2.putText(image, cam_id, (10, 24), cv2.FONT_HERSHEY_SIMPLEX, 0.75, (255, 255, 255), 2, cv2.LINE_AA)
    return image


def make_camera_mosaic(panels: Sequence[np.ndarray]) -> np.ndarray:
    if not panels:
        return placeholder_image(960, 540, 'no cameras')
    if len(panels) == 6:
        rows = [panels[:3], panels[3:]]
    else:
        cols = int(math.ceil(math.sqrt(len(panels))))
        rows = [panels[i:i + cols] for i in range(0, len(panels), cols)]

    row_images = []
    for row in rows:
        max_h = max(img.shape[0] for img in row)
        max_w = max(img.shape[1] for img in row)
        row_images.append(np.concatenate([pad_to_shape(img, max_h, max_w) for img in row], axis=1))
    max_row_w = max(img.shape[1] for img in row_images)
    return np.concatenate([pad_to_shape(img, img.shape[0], max_row_w) for img in row_images], axis=0)


def infer_bev_range(infos: Sequence[Dict], margin: float = 5.0) -> Tuple[float, float, float, float]:
    """Infer a stable BEV display range from all boxes in the pkl."""
    all_xy = []
    for info in infos:
        boxes = to_numpy(info.get('gt_boxes', np.zeros((0, 7), dtype=np.float32)))
        if boxes.size:
            all_xy.append(corners_from_boxes(boxes)[:, :, :2].reshape(-1, 2))
    if not all_xy:
        return -50.0, -50.0, 80.0, 50.0
    xy = np.concatenate(all_xy, axis=0)
    x_min, y_min = np.min(xy, axis=0) - margin
    x_max, y_max = np.max(xy, axis=0) + margin
    x_min, y_min = min(float(x_min), -10.0), min(float(y_min), -30.0)
    x_max, y_max = max(float(x_max), 50.0), max(float(y_max), 30.0)
    if x_max - x_min < 60:
        center = (x_max + x_min) / 2
        x_min, x_max = center - 30, center + 30
    if y_max - y_min < 60:
        center = (y_max + y_min) / 2
        y_min, y_max = center - 30, center + 30
    return x_min, y_min, x_max, y_max


def bev_to_pixel(xy: np.ndarray, bev_range: Tuple[float, float, float, float], size: int) -> np.ndarray:
    x_min, y_min, x_max, y_max = bev_range
    x, y = xy[:, 0], xy[:, 1]
    # Image up is vehicle front (+x), image left is vehicle left (+y).
    u = (y_max - y) / max(y_max - y_min, 1e-6) * (size - 1)
    v = (x_max - x) / max(x_max - x_min, 1e-6) * (size - 1)
    return np.stack([u, v], axis=1)


def draw_bev_grid(image: np.ndarray, bev_range: Tuple[float, float, float, float]) -> None:
    size = image.shape[0]
    x_min, y_min, x_max, y_max = bev_range
    grid_color = (45, 45, 45)
    for x in range(int(math.floor(x_min / 10) * 10), int(math.ceil(x_max / 10) * 10) + 1, 10):
        pts = bev_to_pixel(np.array([[x, y_min], [x, y_max]], dtype=np.float32), bev_range, size).astype(int)
        cv2.line(image, tuple(pts[0]), tuple(pts[1]), grid_color, 1)
    for y in range(int(math.floor(y_min / 10) * 10), int(math.ceil(y_max / 10) * 10) + 1, 10):
        pts = bev_to_pixel(np.array([[x_min, y], [x_max, y]], dtype=np.float32), bev_range, size).astype(int)
        cv2.line(image, tuple(pts[0]), tuple(pts[1]), grid_color, 1)

    origin = bev_to_pixel(np.array([[0.0, 0.0]], dtype=np.float32), bev_range, size)[0].astype(int)
    cv2.circle(image, tuple(origin), 5, (255, 255, 255), -1)
    x_axis = bev_to_pixel(np.array([[0.0, 0.0], [10.0, 0.0]], dtype=np.float32), bev_range, size).astype(int)
    y_axis = bev_to_pixel(np.array([[0.0, 0.0], [0.0, 10.0]], dtype=np.float32), bev_range, size).astype(int)
    cv2.arrowedLine(image, tuple(x_axis[0]), tuple(x_axis[1]), (0, 255, 0), 2, tipLength=0.25)
    cv2.arrowedLine(image, tuple(y_axis[0]), tuple(y_axis[1]), (255, 0, 0), 2, tipLength=0.25)
    cv2.putText(image, 'x front', tuple(x_axis[1] + np.array([5, -5])), cv2.FONT_HERSHEY_SIMPLEX, 0.55, (0, 255, 0), 2, cv2.LINE_AA)
    cv2.putText(image, 'y left', tuple(y_axis[1] + np.array([5, -5])), cv2.FONT_HERSHEY_SIMPLEX, 0.55, (255, 0, 0), 2, cv2.LINE_AA)


def render_bev_panel(
    boxes: np.ndarray,
    names: Sequence[str],
    class_names: Sequence[str],
    bev_range: Tuple[float, float, float, float],
    size: int,
) -> np.ndarray:
    image = np.zeros((size, size, 3), dtype=np.uint8)
    draw_bev_grid(image, bev_range)
    for box_corners, box, name in zip(corners_from_boxes(boxes), boxes, names):
        color = class_color(str(name), class_names)
        pts = bev_to_pixel(box_corners[:4, :2], bev_range, size).astype(np.int32)
        cv2.polylines(image, [pts], True, color, 2, cv2.LINE_AA)
        center = np.array([[box[0], box[1]]], dtype=np.float32)
        yaw = float(box[6])
        front = center + np.array([[math.cos(yaw), math.sin(yaw)]], dtype=np.float32) * max(float(box[3]), 1.0)
        arrow = bev_to_pixel(np.concatenate([center, front], axis=0), bev_range, size).astype(np.int32)
        cv2.arrowedLine(image, tuple(arrow[0]), tuple(arrow[1]), color, 2, tipLength=0.25)
        label_pt = bev_to_pixel(center, bev_range, size)[0].astype(int)
        cv2.putText(image, str(name), tuple(label_pt + np.array([4, -4])), cv2.FONT_HERSHEY_SIMPLEX, 0.45, color, 1, cv2.LINE_AA)
    x_min, y_min, x_max, y_max = bev_range
    summary = f'BEV x[{x_min:.1f},{x_max:.1f}] y[{y_min:.1f},{y_max:.1f}]'
    cv2.rectangle(image, (0, 0), (size, 34), (0, 0, 0), -1)
    cv2.putText(image, summary, (10, 24), cv2.FONT_HERSHEY_SIMPLEX, 0.55, (255, 255, 255), 2, cv2.LINE_AA)
    return image


def render_info(
    info: Dict,
    data_root: Path,
    class_names: Sequence[str],
    camera_ids: Optional[Sequence[str]],
    camera_width: int,
    bev_range: Tuple[float, float, float, float],
    bev_size: int,
    undistort: bool,
    undistort_alpha: float,
    min_depth: float,
    no_bev: bool,
) -> np.ndarray:
    boxes = to_numpy(info.get('gt_boxes', np.zeros((0, 7), dtype=np.float32)))
    names = [str(x) for x in list(info.get('gt_names', []))]
    panels = [
        render_camera_panel(info, cam_id, data_root, boxes, names, class_names, camera_width, undistort, undistort_alpha, min_depth)
        for cam_id in choose_camera_order(info, camera_ids)
    ]
    mosaic = make_camera_mosaic(panels)
    token = str(info.get('token', 'unknown'))
    cv2.rectangle(mosaic, (0, 0), (min(mosaic.shape[1], 900), 34), (0, 0, 0), -1)
    cv2.putText(mosaic, f'{token} | boxes={len(boxes)}', (10, 24), cv2.FONT_HERSHEY_SIMPLEX, 0.65, (255, 255, 255), 2, cv2.LINE_AA)
    if no_bev:
        return mosaic
    bev = render_bev_panel(boxes, names, class_names, bev_range, bev_size)
    bev = cv2.resize(bev, (mosaic.shape[0], mosaic.shape[0]), interpolation=cv2.INTER_AREA)
    return np.concatenate([mosaic, bev], axis=1)


def selected_infos(infos: Sequence[Dict], start_index: int, stride: int, max_frames: Optional[int]) -> Iterable[Tuple[int, Dict]]:
    count = 0
    for idx in range(max(start_index, 0), len(infos), max(stride, 1)):
        if max_frames is not None and count >= max_frames:
            break
        yield idx, infos[idx]
        count += 1


def quat_wxyz_to_matrix(quat) -> np.ndarray:
    """Small local quaternion helper for pkl pose sanity checks.

    The converter writes frame poses as ``[w, x, y, z]`` to match nuScenes-style
    metadata.  This visualizer does not import dataset code, so it keeps a tiny
    duplicate helper here for command-line inspection.
    """
    quat = np.asarray(quat, dtype=np.float32).reshape(4)
    norm = np.linalg.norm(quat)
    if norm <= 0:
        raise ValueError('zero-norm quaternion')
    w, x, y, z = quat / norm
    return np.array([
        [1 - 2 * (y * y + z * z), 2 * (x * y - z * w), 2 * (x * z + y * w)],
        [2 * (x * y + z * w), 1 - 2 * (x * x + z * z), 2 * (y * z - x * w)],
        [2 * (x * z - y * w), 2 * (y * z + x * w), 1 - 2 * (x * x + y * y)],
    ], dtype=np.float32)


def info_lidar2global(info: Dict) -> Optional[Tuple[np.ndarray, np.ndarray]]:
    """Read one frame pose from converter pkl.

    The returned transform maps lidar-frame coordinates to the clip reference
    frame, already expressed in Fast-BEV axes.  ``None`` means the pkl can still
    be visualized frame-by-frame but cannot be temporally compensated like the
    original Fast-BEV nuScenes pipeline.
    """
    rot = info.get('lidar2global_rotation', info.get('ego2global_rotation'))
    tran = info.get('lidar2global_translation', info.get('ego2global_translation'))
    if rot is None or tran is None:
        return None
    return quat_wxyz_to_matrix(rot), np.asarray(tran, dtype=np.float32).reshape(3)


def check_temporal_poses(infos: Sequence[Dict], max_items: int) -> None:
    """Log adjacent-frame relative motion for quick temporal sanity checks.

    This does not replace image overlay inspection.  It simply confirms that the
    pkl contains non-empty pose fields and that ``prev`` frames can be transformed
    into their key-frame lidar coordinates.  For a static parked vehicle, values
    may be close to zero; for a moving clip, they should vary smoothly.
    """
    checked = 0
    for info in infos:
        if checked >= max_items:
            break
        if not info.get('prev'):
            continue
        key_pose = info_lidar2global(info)
        prev_pose = info_lidar2global(info['prev'][0])
        if key_pose is None or prev_pose is None:
            logger.warning('token=%s has prev but missing pose fields', info.get('token'))
            checked += 1
            continue
        key_r, key_t = key_pose
        prev_r, prev_t = prev_pose
        key_from_prev_r = key_r.T @ prev_r
        key_from_prev_t = key_r.T @ (prev_t - key_t)
        yaw = math.atan2(key_from_prev_r[1, 0], key_from_prev_r[0, 0])
        logger.info(
            'pose_check token=%s prev=%s dt_us=%s key_from_prev_t=%s yaw=%.6f rad',
            info.get('token'),
            info['prev'][0].get('token'),
            int(info.get('timestamp', 0)) - int(info['prev'][0].get('timestamp', 0)),
            np.array2string(key_from_prev_t, precision=4),
            yaw)
        checked += 1
    if checked == 0:
        logger.warning('No temporal pose pairs checked; pkl may have only one frame or no prev links.')


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description='Visualize Fast-BEV CustomMultiViewDataset pkl ground truth.',
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument('--pkl', required=True, help='Path to converter output pkl')
    parser.add_argument('--data-root', required=True, help='Root used by converter --data-path; relative image paths are resolved under this directory')
    parser.add_argument('--output-dir', required=True, help='Directory for frames and optional video')
    parser.add_argument('--camera-ids', nargs='+', default=None, help='Camera ids to draw; default uses a six-camera inspection order')
    parser.add_argument('--start-index', type=int, default=0, help='First info index to visualize')
    parser.add_argument('--stride', type=int, default=1, help='Visualize every Nth info')
    parser.add_argument('--max-frames', type=int, default=100, help='Maximum number of frames to render; use -1 for all')
    parser.add_argument('--camera-width', type=int, default=640, help='Width of each camera tile before mosaicing')
    parser.add_argument('--bev-size', type=int, default=700, help='BEV panel size before resizing to mosaic height')
    parser.add_argument('--bev-range', nargs=4, type=float, metavar=('X_MIN', 'Y_MIN', 'X_MAX', 'Y_MAX'), default=None, help='Fixed BEV display range. If omitted, infer from all pkl boxes.')
    parser.add_argument('--no-bev', action='store_true', help='Only save camera mosaic, without BEV panel')
    parser.add_argument('--undistort', action='store_true', help='Undistort images before drawing and use OpenCV new_K for projection')
    parser.add_argument('--undistort-alpha', type=float, default=0.0, help='OpenCV undistort alpha; 0 crops invalid pixels, 1 keeps full FOV')
    parser.add_argument('--min-depth', type=float, default=0.1, help='Do not draw projected edges behind the camera')
    parser.add_argument('--fps', type=int, default=10, help='Output video fps')
    parser.add_argument('--no-video', action='store_true', help='Do not write visualization.mp4')
    parser.add_argument('--image-ext', default='jpg', choices=['jpg', 'png'], help='Per-frame image format')
    parser.add_argument('--check-poses', action='store_true', help='Print key/prev relative pose checks before rendering')
    parser.add_argument('--pose-check-count', type=int, default=10, help='Number of key/prev pose pairs to log when --check-poses is enabled')
    parser.add_argument('--log-level', default='INFO', choices=['DEBUG', 'INFO', 'WARNING', 'ERROR'])
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    logging.getLogger().setLevel(getattr(logging, args.log_level))

    pkl_path = Path(args.pkl)
    data_root = Path(args.data_root)
    output_dir = Path(args.output_dir)
    frame_dir = output_dir / 'frames'
    frame_dir.mkdir(parents=True, exist_ok=True)

    infos, metadata = load_fastbev_pkl(pkl_path)
    class_names = get_class_names(metadata, infos)
    max_frames = None if args.max_frames is not None and args.max_frames < 0 else args.max_frames
    bev_range = tuple(args.bev_range) if args.bev_range else infer_bev_range(infos)

    logger.info('Loaded %d infos from %s', len(infos), pkl_path)
    logger.info('metadata.coordinate=%s', metadata.get('coordinate', 'unknown'))
    logger.info('data_root=%s', data_root)
    logger.info('class_names=%s', class_names)
    logger.info('bev_range=%s', bev_range)
    if args.check_poses:
        check_temporal_poses(infos, args.pose_check_count)

    writer = None
    video_path = output_dir / 'visualization.mp4'
    rendered = 0
    iterator = list(selected_infos(infos, args.start_index, args.stride, max_frames))

    for pkl_index, info in tqdm(iterator, total=len(iterator), desc='visualizing'):
        canvas = render_info(
            info=info,
            data_root=data_root,
            class_names=class_names,
            camera_ids=args.camera_ids,
            camera_width=args.camera_width,
            bev_range=bev_range,
            bev_size=args.bev_size,
            undistort=args.undistort,
            undistort_alpha=args.undistort_alpha,
            min_depth=args.min_depth,
            no_bev=args.no_bev,
        )
        token = sanitize_filename(info.get('token', pkl_index))
        frame_path = frame_dir / f'{rendered:06d}_{token}.{args.image_ext}'
        cv2.imwrite(str(frame_path), canvas)

        if not args.no_video:
            if writer is None:
                h, w = canvas.shape[:2]
                fourcc = cv2.VideoWriter_fourcc(*'mp4v')
                writer = cv2.VideoWriter(str(video_path), fourcc, args.fps, (w, h))
                logger.info('Video writer: %s %dx%d @ %dfps', video_path, w, h, args.fps)
            writer.write(canvas)
        rendered += 1

    if writer is not None:
        writer.release()
    logger.info('Rendered %d frames to %s', rendered, frame_dir)
    if not args.no_video:
        logger.info('Video saved to %s', video_path)


if __name__ == '__main__':
    main()
